config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :users
  end

  resources :roles

  resources :groups do
    resources :posts do
      resources :comments
    end
  end

  root "groups#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, counter_cache: true
  #belongs_to :user
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  paginates_per 5

  def editable_by?(user)
    user && user == owner
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  load_and_authorize_resource only: [:new, :edit, :update]


  def index
    #@comments = Comment.all
    @comments = Comment.page params[:page]
  end

  def show
  end

  def new
    #@comment = Comment.new
    @group = Group.find(params[:group_id])
    @post = @group.posts.find(params[:post_id])
    @comment = @post.comments.new
  end

  def edit
  end

  def create
    #@comment = Comment.new(comment_params)
    @group = Group.find(params[:group_id])
    @post = @group.posts.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        #format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.html { redirect_to group_post_path(@group,@post), notice: '留言已建立！' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        #format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.html { redirect_to group_post_path(@group,@post), notice: '留言已更新！' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      #format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.html { redirect_to group_post_path(@group,@post), notice: '留言已刪除！' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      #@comment = Comment.find(params[:id])
      @group = Group.find(params[:group_id])
      @post = @group.posts.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%# form_for(@comment) do |f| %>
<%= bootstrap_form_for([@group,@post,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>請修正 <%= @comment.errors.count %> 項錯誤！</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class='col-lg-12'>
      <%# f.text_area :content, label: '留言' %>
      <%= f.kindeditor :content, label: '留言' %>
    </div>
    <div class='col-lg-12'>
    <br>
    <%= f.hidden_field :group_id, value: @comment.post.group_id %>
    <%= f.hidden_field :post_id, value: @comment.post_id %>
    <%= f.submit '送出', class: 'btn btn-lg btn-primary' %>
    <%= link_to '回上頁', group_post_path(@group,@post), class: 'btn btn-lg btn-default' %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>編輯留言</h1>

<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>新增留言</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'><h3><%= @post.title %></h3></div>
  <div class='panel-body'><%= sanitize @comment.content %></div>
</div>

<% if can? :update, Comment %>
  <%= link_to '編輯', edit_group_post_comment_path(@group,@post,@comment), class: 'btn btn-lg btn-primary' %>
<% end %>
<%= link_to '回上頁', group_post_path(@group,@post), class: 'btn btn-lg btn-default' %>