config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :users
  end

  resources :roles

  resources :groups do
    resources :posts do
      resources :comments
    end
  end

  root "groups#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, :presence => true
  has_many :posts
  #belongs_to :user
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  paginates_per 10

  def editable_by?(user)
    user && user == owner
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  load_and_authorize_resource only: [:new]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    #@posts = @group.posts
    @posts = @group.posts.page params[:page] #Kaminari分頁功能
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: '群組已建立！' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: '群組已更新！' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: '群組已刪除！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>請修正 <%= @group.errors.count %> 項錯誤！</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '群組名稱' %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit '送出', class: 'btn btn-lg btn-primary' %>
    <%= link_to '回上頁', groups_path, class: 'btn btn-lg btn-default' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>編輯群組</h1>
<%= render 'form' %>

app/views/groups/index.html.erb
<h1>群組列表</h1>

<table class="table table-hover">
  <thead>
    <tr bgcolor='#EDEDED'><th>No</th><th>群組名稱</th><th>文章數量</th><th>操作</th></tr>
  </thead>

  <tbody>
    <% @groups.each_with_index do |group,index| %>
      <tr><td><%= index+1 %></td>
        <td width='70%'><%= link_to(group.name, group_path(group)) %></td>
        <td><span class='badge'><%= group.posts_count %></span></td>
        <td>
          <% if can? :destroy, Group %>
            <%= link_to '修改', edit_group_path(group), class: 'btn btn-xs btn-warning' %>
          <% end %>
          <% if can? :destroy, Group %>
            <%= link_to '刪除', group, method: :delete, data: { confirm: '確定要刪除？' }, class: 'btn btn-xs btn-danger' %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user && current_user.role.name == 'Admin' %>
<% if can? :create, Group %>
  <%= link_to '新增群組', new_group_path, class: 'btn btn-lg btn-primary' %>
<% end %>
<% end %>

app/views/groups/new.html.erb
<h1>新增群組</h1>
<%= render 'form' %>

app/views/groups/show.html.erb
<div class="jumbotron">
  <font class="h1"><%= @group.name %></font>
</div>

<table class='table table-hover'>
<thead>
  <tr><td width='20'>No.</td><td>文章標題</td><td>作者</td><td>發表日期</td><td>留言數</td></tr>
</thead>
<tbody>
<% @posts.each_with_index do |post,index| %>
<tr><td><%= index+1 %></td>
    <td width='60%'><%= link_to(truncate(post.title, length: 36, ommision: '...'), group_post_path(post.group, post)) %></td>
    <td><%= post.owner.name %></td>
    <td><%= post.created_at.strftime("%b %d, %Y %H:%M") %></td>
    <td><span class='badge'><%= post.comments_count %></span></td></tr>
<% end %>
</tbody>
</table>
<%= paginate @posts %>
<br>
<% if can? :create, Post %>
  <%= link_to '新增文章', new_group_post_path(@group), class: 'btn btn-lg btn-primary' %>
<% end %>
<%= link_to '回首頁', root_path, class: 'btn btn-lg btn-default' %>