config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope '/admin' do
    resources :users
  end

  resources :roles

  resources :groups do
    resources :posts do
      resources :comments
    end
  end

  root "groups#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, :presence => true
  belongs_to :group, counter_cache: true
  #belongs_to :user
  belongs_to :owner, :class_name => "User", :foreign_key => :user_id
  has_many :comments
  paginates_per 10

  def editable_by?(user)
    user && user == owner
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  load_and_authorize_resource only: [:new]

  def index
    #@posts = Post.all
    @posts = Post.page params[:page] #Kaminari分頁功能
  end

  def show
    #@comments = @post.comments.all
    @comments = @post.comments.page params[:page] #Kaminari分頁功能
  end

  def new
    #@post = Post.new
    @group = Group.find(params[:group_id])
    @post = @group.posts.new
  end

  def edit
  end

  def create
    #@post = Post.new(post_params)
    @group = Group.find(params[:group_id])
    @post = @group.posts.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.html { redirect_to @group, notice: '文章已建立！' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        #format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.html { redirect_to group_path(@group), notice: '文章已更新！' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      #format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.html { redirect_to group_path(@group), notice: '文章已刪除！' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      #@post = Post.find(params[:id])
      @group = Group.find(params[:group_id])
      @post = @group.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :group_id, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%# form_for(@post) do |f| %>
<%= bootstrap_form_for([@group,@post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>請修正 <%= @post.errors.count %> 項錯誤！</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class='col-lg-12'>
      <%= f.text_field :title, label: '標題' %>
    </div>
    <div class='col-lg-12'>
      <%# f.text_area :content, label: '內文', size: '10x5' %>
      <%= f.kindeditor :content, label: '內文' %>
    </div>
    <%= f.hidden_field :group_id, value: @post.group_id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit '送出', class: 'btn btn-lg btn-primary' %>
    <%= link_to '回上頁', group_path(@group), class: 'btn btn-lg btn-default' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>編輯文章</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Group</th>
      <th>作者</th>
      <th>操作</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.group %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Show', post %>
            <%= link_to 'Edit', edit_post_path(post) %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>新增文章</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class='panel panel-default'>
<div class='panel-heading'><h3><%= @post.title %></h3><h5>作者：<%= @post.owner.name %></h5></div>
  <div class='panel-body'><%= sanitize @post.content %></div>
</div>

 <div class='row'>
   <div class='col-md-12'>

<table class='table table-hover'>
<colgroup>
  <col class="col-md-1">
  <col class="col-md-6">
  <col class="col-md-1">
  <col class="col-md-2">
  <col class="col-md-2">
</colgroup>
<tr bgcolor='#CECECE'><th>No.</th><th>訪客留言</th><th>作者</th><th>留言時間</th><th>操作</th></tr>
<% @comments.each_with_index do |comment,index| %>
<tr><td><%= index+1 %></td>
<td><%= sanitize comment.content %></td>
<td><%= comment.owner.name %></td>
<td><%= comment.created_at.strftime("%b %d, %Y %H:%M") %></td>

<td>
  <%= link_to '詳細', group_post_comment_path(@group,@post,comment.id), class: 'btn btn-xs btn-success' %>

  <% if current_user && comment.editable_by?(current_user) %>
  <% if can? :update, Comment %>
    <%= link_to '編輯', edit_group_post_comment_path(@group,@post,comment.id), class: 'btn btn-xs btn-warning' %>
  <% end %>
  <% end %>

  <% if can? :destroy, Comment %>
    <%= link_to '刪除', group_post_comment_path(@group,@post,comment.id), method: :delete, data: { confirm: '確定要刪除嗎？' }, class: 'btn btn-xs btn-danger' %></td></tr>
  <% end %>
<% end %>
</table>

  </div>
  </div>

<%= paginate @comments %><br>

<% if can? :create, Comment %>
  <%= link_to '新增留言', new_group_post_comment_path(@group,@post,@comment), class: 'btn btn-lg btn-success' %>
<% end %>
<hr>

<% if current_user && @post.editable_by?(current_user) %>
<% if can? :update, Post %>
  <%= link_to '編輯', edit_group_post_path(@group,@post), class: 'btn btn-lg btn-primary' %>
<% end %>
<% end %>

<% if can? :destroy, Post %>
  <%= link_to '刪除', group_post_path(@group,@post), method: :delete, data: { confirm: '確定要刪除嗎？' }, class: 'btn btn-lg btn-danger' %>
<% end %>
<%= link_to '回上頁', group_path(@group), class: 'btn btn-lg btn-default' %>